### ISSUE TITLE
 java.lang.NoSuchMethodError: 'org.apache.logging.log4j.LogBuilder org.apache.logging.log4j.Logger.atDebug()

### ISSUE THREAD

**Issue by sailyfirm** [quarkiverse/quarkus-poi#69] opened 2023-06-28 03:27 UTC
Quarkus 3.0 , I use poi to hander excel file , quarkus logging implements is jboss logging  , poi  is log4j-api 2.18.0 ,  

```
at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.parseRelationshipsPart(PackageRelationshipCollection.java:309)
	at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:160)
	at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:130)
	at org.apache.poi.openxml4j.opc.PackagePart.loadRelationships(PackagePart.java:565)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:751)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:322)
	at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:59)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:290)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:286)
```

**Comment by gastaldi** [comment] 2023-06-28 04:20
Why was this issue closed?

**Comment by melloware** [comment] 2023-06-28 11:35
@sailyfirm please respond with what resolved your issue so we can properly close this ticket or investigate if its a real issue?

**Comment by gastaldi** [comment] 2023-06-30 03:33
Closing as the issue is incomplete. Please reopen when you have more info and a reproducer

**Closed by gastaldi** 2023-06-30 03:33 UTC

**Comment by sailyfirm** [comment] 2023-06-30 14:43
sorry !  finnaly I found a conflicting log4j class in another jar ,because it a fat jar (dremio jdbc driver) with log4j api .  so I closed it  .
