### ISSUE TITLE
poi extension Build native image error

### ISSUE THREAD

**Issue by Sparkel-wsl** [quarkiverse/quarkus-poi#86] opened 2023-11-15 01:06 UTC
Describe the bug
In my work, I needed to export data to excel, so I adopted quarkus-poi, and there were no errors during the test. When building a local executable, "Windows AWT integration is not ready in native images and Java" is thrown. Lang. UnsatisfiedLinkError: There is no awt in java.library.path.'. But I only want to use excel related functions in poi, not AWT related functions.

Expected behavior
Expect the behavior to build successfully because I'm not going to use the awt functionality

Actual behavior
Building a native executable throws:'Windows AWT integration is not ready in native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.'

How to Reproduce?
1:Import the poi extension
<dependency> <groupId>io.quarkiverse.poi</groupId> <artifactId>quarkus-poi</artifactId> <version>2.0.3</version> </dependency>
2:mvnw package -Dnative

Output of uname -a or ver
Microsoft Windows [版本 10.0.19045.3570]

Output of java -version
openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

Mandrel or GraalVM version (if different from Java)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

Quarkus version or git rev
3.2.0.Final

Build tool (ie. output of mvnw --version or gradlew --version)
Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: D:\apache-maven-3.9.2
Java version: 17.0.6, vendor: GraalVM Community, runtime: D:\graalvm-ce-java17-22.3.1
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Additional information
io.quarkiverse.poi quarkus-poi 2.0.3

**Comment by melloware** [comment] 2023-11-15 01:12
Hmm can you create a small reproducer?  Our Integration tests run in native mode and are passing.

**Comment by Sparkel-wsl** [comment] 2023-11-15 01:34
> 嗯，你能创建一个小型复制器吗？我们的集成测试在本机模式下运行并且正在通过。
> 
> 我还在我的应用程序中以本机模式成功使用它。

Ok, I use quarkus-hibernate-orm as a test case, and the project is on gitee. [https://gitee.com/wsl__cn/quarkus-poi-issues.git](url)

**Comment by melloware** [comment] 2023-11-15 01:59
Ok great I will check it!

**Comment by melloware** [comment] 2023-11-15 14:20
@Sparkel-wsl I don't see any code here: https://gitee.com/wsl__cn/quarkus-poi-issues/blob/master/hibernate-orm-quickstart/src/main/java/org/acme/hibernate/orm/Controller/TestController.java That our integration tests aren't already testing and passing in Native mode.

Did you forget to check something in?

**Comment by Sparkel-wsl** [comment] 2023-11-16 01:16
@melloware I did not use poi related functions on the test case, even though I did not use poi related functions, just to repeat the error. However, when building native executables, the error mentioned above is still displayed.

**Comment by melloware** [comment] 2023-11-16 02:10
Well this is the POI extension and without a POI issue I will close this. I am not having any Native Image issue and the nightly build is also passing on Native mode.

**Comment by melloware** [comment] 2023-11-16 02:13
Don't know why but it looks like you are having this Graal issue https://github.com/oracle/graal/issues/2842

**Closed by melloware** 2023-11-16 02:13 UTC
Labels: question
